export interface Provider {
  id: string;
  name: string;
  baseUrl: string;
  apiKey: string;
}

export interface ModelCfg {
  id: string;
  providerId: string;
  modelId: string;
  label: string;
}

/** OpenAI-style reasoning effort. Only sent for models that support it. */
export type ReasoningEffort = "minimal" | "low" | "medium" | "high";

export type Role = "system" | "user" | "assistant";

export type ToolName =
  | "read_file"
  | "list_dir"
  | "write_file"
  | "edit_file"
  | "delete_file";

export type ToolStatus =
  | "running"
  | "awaiting" // waiting for the user's permission
  | "ok"
  | "error"
  | "denied";

/** One tool call requested by the model within an assistant turn. */
export interface ToolStep {
  /** tool_call_id from the API (used to return the result). */
  id: string;
  name: string;
  /** Raw JSON arguments string from the model. */
  args: string;
  /** Resolved target path for file ops (display). */
  path?: string;
  status: ToolStatus;
  /** Text result fed back to the model (and shown when expanded). */
  result?: string;
  /** Unified diff (for write/edit), serialized as DiffLine[] JSON. */
  diff?: string;
}

export interface ChatMessage {
  id: string;
  role: Role;
  content: string;
  /** Reasoning/thinking tokens from the model (shown muted when enabled). */
  reasoning?: string;
  /** Attached file contents injected into context (from @file mentions). */
  fileContext?: string;
  /** Tool calls the assistant made in this turn (agent mode). */
  toolSteps?: ToolStep[];
  /** true while tokens are still streaming into this message */
  streaming?: boolean;
  error?: boolean;
}

export type SessionKind = "session" | "folder";

export interface Session {
  id: string;
  title: string;
  kind: SessionKind;
  /** Absolute path of the working folder this chat is bound to (if any). */
  folderPath?: string | null;
  /** Display name of the working folder (basename of folderPath). */
  folderName?: string | null;
  /** true once the title has been auto-generated by the model. */
  autoTitled?: boolean;
  createdAt: number;
  updatedAt: number;
  messages: ChatMessage[];
}
